# Site settings
title: Digitālais nekustamā īpašuma brokeris | Brokalys.com
description: Digitālais nekustamā īpašuma brokeris

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 2973388149
# data-ad-client: ca-pub-9204963049240271
# google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-24636123-15"

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - publish.js
  - README.md
  - Rakefile

gems: 
  - jekyll-paginate
